import type {
  CapabilityDescriptor,
  EditProject,
  Product,
  Timeline,
} from "@auto-video/shared";

export const demoProduct: Product = {
  sku: "DEMO-SKU-001",
  name: "晨光便携榨汁杯",
  sellingPoints: ["轻巧便携", "快速鲜榨", "一冲即净"],
  aliases: ["便携榨汁机", "随行果汁杯"],
  referenceImages: [],
};

export const demoTimeline: Timeline = {
  schemaVersion: 1,
  id: "timeline-demo-a",
  title: "通勤也能喝到新鲜果汁",
  productSku: demoProduct.sku,
  status: "needs_review",
  width: 1080,
  height: 1920,
  fps: 30,
  durationInFrames: 720,
  brand: {
    name: "MORNING LAB",
    primary: "#d9ff4f",
    accent: "#ff7657",
    text: "#f8fafc",
    mutedText: "#b8c0cf",
    fontFamily: "PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif",
  },
  clips: [
    {
      id: "clip-hook",
      assetShotId: null,
      startFrame: 0,
      durationInFrames: 120,
      sourceInSeconds: 0,
      sourceOutSeconds: 4,
      label: "早高峰场景",
      sellingPoint: "随时喝到新鲜果汁",
      placeholder: {from: "#17241f", to: "#3f735d"},
    },
    {
      id: "clip-portable",
      assetShotId: null,
      startFrame: 120,
      durationInFrames: 120,
      sourceInSeconds: 0,
      sourceOutSeconds: 4,
      label: "放入通勤包",
      sellingPoint: "轻巧便携",
      placeholder: {from: "#32263f", to: "#78558f"},
    },
    {
      id: "clip-fruit",
      assetShotId: null,
      startFrame: 240,
      durationInFrames: 120,
      sourceInSeconds: 0,
      sourceOutSeconds: 4,
      label: "投入新鲜水果",
      sellingPoint: "新鲜现做",
      placeholder: {from: "#4a261e", to: "#db6242"},
    },
    {
      id: "clip-blend",
      assetShotId: null,
      startFrame: 360,
      durationInFrames: 120,
      sourceInSeconds: 0,
      sourceOutSeconds: 4,
      label: "高速搅打特写",
      sellingPoint: "快速鲜榨",
      placeholder: {from: "#162b4a", to: "#3d80c5"},
    },
    {
      id: "clip-clean",
      assetShotId: null,
      startFrame: 480,
      durationInFrames: 120,
      sourceInSeconds: 0,
      sourceOutSeconds: 4,
      label: "清水冲洗",
      sellingPoint: "一冲即净",
      placeholder: {from: "#14353c", to: "#40a3ac"},
    },
    {
      id: "clip-cta",
      assetShotId: null,
      startFrame: 600,
      durationInFrames: 120,
      sourceInSeconds: 0,
      sourceOutSeconds: 4,
      label: "商品定帧",
      sellingPoint: "今天开始喝点新鲜的",
      placeholder: {from: "#30271d", to: "#a17432"},
    },
  ],
  subtitles: [
    {id: "sub-1", startFrame: 10, endFrame: 112, text: "早上赶时间，也别委屈自己的早餐"},
    {id: "sub-2", startFrame: 130, endFrame: 232, text: "轻巧杯身，随手放进通勤包"},
    {id: "sub-3", startFrame: 250, endFrame: 352, text: "水果切块，加水或牛奶"},
    {id: "sub-4", startFrame: 370, endFrame: 472, text: "按下开关，快速鲜榨"},
    {id: "sub-5", startFrame: 490, endFrame: 592, text: "喝完加水启动，一冲即净"},
    {id: "sub-6", startFrame: 610, endFrame: 710, text: "晨光便携榨汁杯，今天喝点新鲜的"},
  ],
  voiceover: {
    id: "voiceover-demo",
    kind: "voiceover",
    source: null,
    volume: 1,
    state: "not_configured",
  },
  music: {
    id: "music-demo",
    kind: "music",
    source: null,
    volume: 0.18,
    state: "not_configured",
  },
  cta: "现在入手 · 开启新鲜通勤",
};

export const demoProject: EditProject = {
  id: "project-demo-001",
  product: demoProduct,
  scriptPath: "examples/scripts/demo-product.txt",
  variants: [demoTimeline],
  status: "needs_review",
  createdAt: "2026-07-22T00:00:00.000Z",
  updatedAt: "2026-07-22T00:00:00.000Z",
};

export const capabilityDescriptors: CapabilityDescriptor[] = [
  {id: "nas", label: "NAS 素材库", state: "not_configured", detail: "等待挂载路径"},
  {id: "catalog", label: "商品资料表", state: "not_configured", detail: "等待 Excel/CSV 样例"},
  {id: "asset-index", label: "镜头语义索引", state: "not_configured", detail: "等待真实素材"},
  {id: "tts", label: "AI 配音", state: "not_configured", detail: "等待服务商凭证"},
  {id: "music", label: "授权音乐库", state: "not_configured", detail: "等待 NAS 音乐目录"},
  {id: "render-queue", label: "后台渲染队列", state: "unavailable", detail: "框架阶段未实现"},
];
